name: Pychunks Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 90
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
        platform: [ubuntu-latest, windows-latest]
        testfile: [
                   "./test/langchain/test_langchain.py",
                   "./test/llama_index/test_code_splitter.py",
                   "./test/llama_index/test_sentence_splitter.py",
                   "./test/llama_index/test_token_splitter.py",
                  ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -r requirements.txt && python -m pip install -r requirements_dev.txt
    - name: Test
      run: python -m pytest ${{ matrix.testfile }}
